apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |-
    .:53 {
      log . {
        class denial
      }
      cache
      errors
      loadbalance round_robin
      whoami
      health
      prometheus 0.0.0.0:9153
      proxy . 8.8.8.8:53
    }

    cluster.local {
      etcd cluster.local {
        stubzones
        path /skydns
        endpoint https://100.67.151.2:2379 https://100.67.151.3:2379 https://100.67.151.4:2379
        upstream 8.8.8.8:53 8.8.4.4:53
        debug
      }
      errors
      log
    }

