apiVersion: v1
kind: Service
metadata:
  name: kube-coredns-udp
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  externalIPs:
  - 100.67.151.8
  ports:
  - name: dns
    port: 53
    protocol: UDP
  #- name: metrics
  #  port: 9153
  #  protocol: TCP

